language: php
php:
- '7.0'
env:
  global:
  - secure: "Zj0PWjNnZl8iDcKDG9cn1570wlAM/PpWQBd/ivfDzX1z82+y20lx2UNR1x5XIuTAilUcH0yU4x+Nmg5pizJkEyzereuuRwDHccuCXOgIvKrJYWUqj0N0B5u+tQG2eUccWT1KVXnO5d0qqcXNhBA3jg5Fdt6j7faUtGzHHesYQOqhV2Q+f4FVSFQQxPvOHmS6TvyjvbllHWSY8yOc6mHgzayx33E+ZyINGLliUv7FjmEX1adOl8aGXJnsBOZ6kbMXw1UMEBCyYqwUh6txP1XWnVmBhiVVqUfCVtNzl0k4wf6WifJJnpAmEfwKIlelMYybRD3W8MwN/7EigTIjQI346MzpbwVPSQFjQDeAuR9bXKqA93kGxPY6xO/KMXmnMits0HkifO58yB2pyIXz1syosjNgAEHXiPwvDj6wzzm/TGa+hzC2J04jCERI5SKiLx6RogcncYGU+YrxfyIrSy7RyumLJ5Gmd4Iho70DiZoSCxggHIndvK81evd2d3efUEPzp/05eqSb4F+eP47YE8ehajd0REhZQPrhqolcPclu+T7XW+nVaEkQzlYEIeRk3fSm98qojWil8XuTBhFsMUlMeMSNmJvmgrydAgnviZHAN6qTyTwr9gFZwZonS+0y0pKETNb9YLkLVKibUsDSoM1evq1w45VHwPG3AqNYWbm2meA=" # PANTHEON_REMOTE
  - secure: "nIKw/R44+dRdWCq2v21XZZVnmlN0fcf0CV4a671VhDL7AqWhFgzxijMPBfJ/0zJi6Xk8zAz63py0B8Yl3ET5MwfV7ZGYC4KJjZ4DeTZJZ+bqKrB6saetfsJEVEmC77XFYw4uOjOP7CAbp5DGwt+dNyj1sTvi+Ai390NnqBzFekX26/3bs5wKl0YgOKvrwEcbSQOFzHF1nTSaaZQdRWcjDyffB3DVVkN07hUdgJNW3abMpWbWnKpfpL1GYckKzCYe+/XcVAgogsiHV+OZuLIlBleZxRMT200qeRMTKs4YjEJPmVFnGMtc0Z7WGgtZOaQerM71Qe1V00ofklaKtDdWMaB9fNRrSeQrzf/ycvBxxVeksvWboDBTkzdNnyHz6dM6TuiR5G0k1RNZepoeZi8MXvyEdyfnpBn9aovBBqLWh3vkf1HYSOudkSCPQZJv8us1q97f6AfiZED9ll5oKsHqAMu5hicSSX9S5r7jzafhP6TdfPJCiTlWAyW8krGJhiqIPDP+iN/4QtM6RlDsOakWL8KnWMomjcygfzofWG8OW6NZBrba1Szit+oerPQxqnUzle5MYlbf7KR0UuhwGWOxDsvKR6sJyHC0CzaLpBoEw3l/usZtlT3pYJJ9VM1KnlLYUZHBz+K5PqQiXjLu1i3J4fZGgku3XWDyEp5fVaAexFc=" # PANTHEON_HOST
  - secure: "noHelujuztBBV0eY/T+/L5HTVcUw+rMHVBOTy3O0eyTUKbMVA/yz465HOSXPoJusRCXfl9cNZnmbVrE9VAOmfXuDJt4y1nRSxqO8zIMQonC0NWr7rk6ziK6PXO7kD46KB9HOjbLfv5vAPkInhbsJI8HJrKWl1b7Tmydb97a1ZdNu99kJFwaqiowlVdgXfrk03zD3PCwBwMpEbRpklWJTnZg3GcBnXSvW0AIeJ42wZdrM8u2hcQlnxinYx6A4mZb86KEcPGImM90fE2TJJFIyvVkMuSiIfopMCu0XqTD2RuRizLX+HKXsngX21MmQ/9b2YLHwg5/6v30zQ3APVhHRZ9ZPpZzsyTEy9NUxwpjhSLWFu8PlDai85kjxIt27rbGugmQ5wNB6T8wDceWaKg8b04F0U4aL9+VeP2kK7TbRrpIbBjDhz708dVADeT1MhUzOKPqMWqz02PGKkdS2bWs7/4Doy7nIpyNvp9lDbq5y0T6728+d/WxLNNBzsmFKoFSDD3FJv3KdQAES7KehQSnS+sk1FaCQx5Dvo/MgYcnc2009z/IgaSGWxMLMPw5KsHSDpai1Pwp+tbLVBg8ovUvdmc3KK3rE/AqhmpBNerGg/pCq8fuGCN9ibC8MBeK2i21DBzC7KN4FHGrKGl/Nc0fLbPNUpG05G49src5PemoAwU8=" # PANTHEON_PORT
script:
- true
before_deploy:
- git remote add pantheon $PANTHEON_REMOTE

# TODO: currrently vulnerable to MITM, could hardcode host keys in here
- ssh-keyscan github.com >> ~/.ssh/known_hosts
- ssh-keyscan -p $PANTHEON_PORT $PANTHEON_HOST >> ~/.ssh/known_hosts

- echo $HOME
- openssl aes-256-cbc -K $encrypted_a212912bf46c_key -iv $encrypted_a212912bf46c_iv -in test-ci-integration.enc -out $HOME/.ssh/id_rsa -d
eploy:
- provider: script
  script: git fetch pantheon && git merge -m "Merge changes from pantheon into github" pantheon/master && git push origin HEAD:master && git push pantheon HEAD:master
  on:
    branch: master
